// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPXsMVedfgzTgVLe72jXQ-viXUVisX7c',
    appId: '1:561796163543:web:f8528ec3ddfef4743bcd92',
    messagingSenderId: '561796163543',
    projectId: 'pawpal-174aa',
    authDomain: 'pawpal-174aa.firebaseapp.com',
    storageBucket: 'pawpal-174aa.firebasestorage.app',
    measurementId: 'G-F8GS74BL3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrdVrO7gwbWETXJG21cQKd2Vi20-eAEg',
    appId: '1:561796163543:android:2776287e3cb143103bcd92',
    messagingSenderId: '561796163543',
    projectId: 'pawpal-174aa',
    storageBucket: 'pawpal-174aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBV1tSUKHC6i7NMPrjGmkXlXUJvjQYzY0',
    appId: '1:561796163543:ios:8308fc573bece9183bcd92',
    messagingSenderId: '561796163543',
    projectId: 'pawpal-174aa',
    storageBucket: 'pawpal-174aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBV1tSUKHC6i7NMPrjGmkXlXUJvjQYzY0',
    appId: '1:561796163543:ios:8308fc573bece9183bcd92',
    messagingSenderId: '561796163543',
    projectId: 'pawpal-174aa',
    storageBucket: 'pawpal-174aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjPXsMVedfgzTgVLe72jXQ-viXUVisX7c',
    appId: '1:561796163543:web:435bebeee753e1fd3bcd92',
    messagingSenderId: '561796163543',
    projectId: 'pawpal-174aa',
    authDomain: 'pawpal-174aa.firebaseapp.com',
    storageBucket: 'pawpal-174aa.firebasestorage.app',
    measurementId: 'G-REYXZZ21BW',
  );

}